### ISSUE TITLE
ROS sudo apt-get not possible?

### ISSUE THREAD

**Issue by ibaranov-cp** [g/grizzly_robot#3]
Hey, 

Wiki states:
sudo apt-get install ros-hydro-grizzly-robot

However, this package does not exist in the repo. Is there a step missing?
(This was the best place I thought to ask this question...)

**Comment by mikepurvis** [comment]
The grizzly_robot and dependent packages for Grizzly are not currently available from `packages.ros.org`. This is primarily because grizzly_robot depends on grizzly_firmware, which is proprietary.

The action item here is to set up the internal packages to be available from `packages.clearpathrobotics.com`. There are several factors gating that; among them, that OSRF have expressed that any packages distributed apart from `packages.ros.org` should not be prefixed with `ros-` or install to `/opt/ros`— our build system should be changed to build with `clearpath-ros-` as the name, and `/opt/clearpath/ros` as the installation prefix.

**Comment by ibaranov-cp** [comment]
Gotcha, thanks.

**Comment by mikepurvis** [comment]
These packages are now available: http://wiki.ros.org/ClearpathRobotics/Packages
